// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
	report "github.com/yyypluto/parkieee-api/internal/report"

	uuid "github.com/google/uuid"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// DailyRevenue provides a mock function with given fields: from, to, zoneID, vehicleTypeID
func (_m *Repo) DailyRevenue(from time.Time, to time.Time, zoneID *uuid.UUID, vehicleTypeID *uuid.UUID) ([]report.DailyRevenue, error) {
	ret := _m.Called(from, to, zoneID, vehicleTypeID)

	if len(ret) == 0 {
		panic("no return value specified for DailyRevenue")
	}

	var r0 []report.DailyRevenue
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, *uuid.UUID, *uuid.UUID) ([]report.DailyRevenue, error)); ok {
		return rf(from, to, zoneID, vehicleTypeID)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, *uuid.UUID, *uuid.UUID) []report.DailyRevenue); ok {
		r0 = rf(from, to, zoneID, vehicleTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]report.DailyRevenue)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time, *uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(from, to, zoneID, vehicleTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ZoneOccupancy provides a mock function with no fields
func (_m *Repo) ZoneOccupancy() ([]report.ZoneOccupancy, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ZoneOccupancy")
	}

	var r0 []report.ZoneOccupancy
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]report.ZoneOccupancy, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []report.ZoneOccupancy); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]report.ZoneOccupancy)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
