// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	auth "github.com/yyypluto/parkieee-api/internal/auth"

	user "github.com/yyypluto/parkieee-api/internal/user"

	uuid "github.com/google/uuid"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

type Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *Repo) EXPECT() *Repo_Expecter {
	return &Repo_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function with given fields: rt
func (_m *Repo) CreateRefreshToken(rt *auth.RefreshToken) error {
	ret := _m.Called(rt)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*auth.RefreshToken) error); ok {
		r0 = rf(rt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type Repo_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - rt *auth.RefreshToken
func (_e *Repo_Expecter) CreateRefreshToken(rt interface{}) *Repo_CreateRefreshToken_Call {
	return &Repo_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", rt)}
}

func (_c *Repo_CreateRefreshToken_Call) Run(run func(rt *auth.RefreshToken)) *Repo_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.RefreshToken))
	})
	return _c
}

func (_c *Repo_CreateRefreshToken_Call) Return(_a0 error) *Repo_CreateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_CreateRefreshToken_Call) RunAndReturn(run func(*auth.RefreshToken) error) *Repo_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: s
func (_m *Repo) CreateSession(s *auth.UserSession) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*auth.UserSession) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type Repo_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - s *auth.UserSession
func (_e *Repo_Expecter) CreateSession(s interface{}) *Repo_CreateSession_Call {
	return &Repo_CreateSession_Call{Call: _e.mock.On("CreateSession", s)}
}

func (_c *Repo_CreateSession_Call) Run(run func(s *auth.UserSession)) *Repo_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.UserSession))
	})
	return _c
}

func (_c *Repo_CreateSession_Call) Return(_a0 error) *Repo_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_CreateSession_Call) RunAndReturn(run func(*auth.UserSession) error) *Repo_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionsByRoleID provides a mock function with given fields: roleID
func (_m *Repo) FindPermissionsByRoleID(roleID uuid.UUID) ([]string, error) {
	ret := _m.Called(roleID)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionsByRoleID")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]string, error)); ok {
		return rf(roleID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []string); ok {
		r0 = rf(roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindPermissionsByRoleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionsByRoleID'
type Repo_FindPermissionsByRoleID_Call struct {
	*mock.Call
}

// FindPermissionsByRoleID is a helper method to define mock.On call
//   - roleID uuid.UUID
func (_e *Repo_Expecter) FindPermissionsByRoleID(roleID interface{}) *Repo_FindPermissionsByRoleID_Call {
	return &Repo_FindPermissionsByRoleID_Call{Call: _e.mock.On("FindPermissionsByRoleID", roleID)}
}

func (_c *Repo_FindPermissionsByRoleID_Call) Run(run func(roleID uuid.UUID)) *Repo_FindPermissionsByRoleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_FindPermissionsByRoleID_Call) Return(_a0 []string, _a1 error) *Repo_FindPermissionsByRoleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindPermissionsByRoleID_Call) RunAndReturn(run func(uuid.UUID) ([]string, error)) *Repo_FindPermissionsByRoleID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshToken provides a mock function with given fields: tokenHash
func (_m *Repo) FindRefreshToken(tokenHash string) (*auth.RefreshToken, error) {
	ret := _m.Called(tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshToken")
	}

	var r0 *auth.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.RefreshToken, error)); ok {
		return rf(tokenHash)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.RefreshToken); ok {
		r0 = rf(tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshToken'
type Repo_FindRefreshToken_Call struct {
	*mock.Call
}

// FindRefreshToken is a helper method to define mock.On call
//   - tokenHash string
func (_e *Repo_Expecter) FindRefreshToken(tokenHash interface{}) *Repo_FindRefreshToken_Call {
	return &Repo_FindRefreshToken_Call{Call: _e.mock.On("FindRefreshToken", tokenHash)}
}

func (_c *Repo_FindRefreshToken_Call) Run(run func(tokenHash string)) *Repo_FindRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repo_FindRefreshToken_Call) Return(_a0 *auth.RefreshToken, _a1 error) *Repo_FindRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindRefreshToken_Call) RunAndReturn(run func(string) (*auth.RefreshToken, error)) *Repo_FindRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function with given fields: id
func (_m *Repo) FindUserByID(id uuid.UUID) (*user.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*user.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *user.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type Repo_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repo_Expecter) FindUserByID(id interface{}) *Repo_FindUserByID_Call {
	return &Repo_FindUserByID_Call{Call: _e.mock.On("FindUserByID", id)}
}

func (_c *Repo_FindUserByID_Call) Run(run func(id uuid.UUID)) *Repo_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_FindUserByID_Call) Return(_a0 *user.User, _a1 error) *Repo_FindUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindUserByID_Call) RunAndReturn(run func(uuid.UUID) (*user.User, error)) *Repo_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function with given fields: username
func (_m *Repo) FindUserByUsername(username string) (*user.User, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*user.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type Repo_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - username string
func (_e *Repo_Expecter) FindUserByUsername(username interface{}) *Repo_FindUserByUsername_Call {
	return &Repo_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", username)}
}

func (_c *Repo_FindUserByUsername_Call) Run(run func(username string)) *Repo_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repo_FindUserByUsername_Call) Return(_a0 *user.User, _a1 error) *Repo_FindUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindUserByUsername_Call) RunAndReturn(run func(string) (*user.User, error)) *Repo_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserRefreshTokens provides a mock function with given fields: userID
func (_m *Repo) RevokeAllUserRefreshTokens(userID uuid.UUID) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_RevokeAllUserRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserRefreshTokens'
type Repo_RevokeAllUserRefreshTokens_Call struct {
	*mock.Call
}

// RevokeAllUserRefreshTokens is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *Repo_Expecter) RevokeAllUserRefreshTokens(userID interface{}) *Repo_RevokeAllUserRefreshTokens_Call {
	return &Repo_RevokeAllUserRefreshTokens_Call{Call: _e.mock.On("RevokeAllUserRefreshTokens", userID)}
}

func (_c *Repo_RevokeAllUserRefreshTokens_Call) Run(run func(userID uuid.UUID)) *Repo_RevokeAllUserRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_RevokeAllUserRefreshTokens_Call) Return(_a0 error) *Repo_RevokeAllUserRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_RevokeAllUserRefreshTokens_Call) RunAndReturn(run func(uuid.UUID) error) *Repo_RevokeAllUserRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: id, replacedBy
func (_m *Repo) RevokeRefreshToken(id uuid.UUID, replacedBy *uuid.UUID) error {
	ret := _m.Called(id, replacedBy)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *uuid.UUID) error); ok {
		r0 = rf(id, replacedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type Repo_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - id uuid.UUID
//   - replacedBy *uuid.UUID
func (_e *Repo_Expecter) RevokeRefreshToken(id interface{}, replacedBy interface{}) *Repo_RevokeRefreshToken_Call {
	return &Repo_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", id, replacedBy)}
}

func (_c *Repo_RevokeRefreshToken_Call) Run(run func(id uuid.UUID, replacedBy *uuid.UUID)) *Repo_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(*uuid.UUID))
	})
	return _c
}

func (_c *Repo_RevokeRefreshToken_Call) Return(_a0 error) *Repo_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_RevokeRefreshToken_Call) RunAndReturn(run func(uuid.UUID, *uuid.UUID) error) *Repo_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: sessionID
func (_m *Repo) RevokeSession(sessionID uuid.UUID) error {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type Repo_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - sessionID uuid.UUID
func (_e *Repo_Expecter) RevokeSession(sessionID interface{}) *Repo_RevokeSession_Call {
	return &Repo_RevokeSession_Call{Call: _e.mock.On("RevokeSession", sessionID)}
}

func (_c *Repo_RevokeSession_Call) Run(run func(sessionID uuid.UUID)) *Repo_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_RevokeSession_Call) Return(_a0 error) *Repo_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_RevokeSession_Call) RunAndReturn(run func(uuid.UUID) error) *Repo_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertLoginStats provides a mock function with given fields: userID, success, ip
func (_m *Repo) UpsertLoginStats(userID uuid.UUID, success bool, ip string) error {
	ret := _m.Called(userID, success, ip)

	if len(ret) == 0 {
		panic("no return value specified for UpsertLoginStats")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, bool, string) error); ok {
		r0 = rf(userID, success, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_UpsertLoginStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertLoginStats'
type Repo_UpsertLoginStats_Call struct {
	*mock.Call
}

// UpsertLoginStats is a helper method to define mock.On call
//   - userID uuid.UUID
//   - success bool
//   - ip string
func (_e *Repo_Expecter) UpsertLoginStats(userID interface{}, success interface{}, ip interface{}) *Repo_UpsertLoginStats_Call {
	return &Repo_UpsertLoginStats_Call{Call: _e.mock.On("UpsertLoginStats", userID, success, ip)}
}

func (_c *Repo_UpsertLoginStats_Call) Run(run func(userID uuid.UUID, success bool, ip string)) *Repo_UpsertLoginStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(bool), args[2].(string))
	})
	return _c
}

func (_c *Repo_UpsertLoginStats_Call) Return(_a0 error) *Repo_UpsertLoginStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_UpsertLoginStats_Call) RunAndReturn(run func(uuid.UUID, bool, string) error) *Repo_UpsertLoginStats_Call {
	_c.Call.Return(run)
	return _c
}

// WriteLoginLog provides a mock function with given fields: l
func (_m *Repo) WriteLoginLog(l *auth.UserLoginLog) error {
	ret := _m.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for WriteLoginLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*auth.UserLoginLog) error); ok {
		r0 = rf(l)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_WriteLoginLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteLoginLog'
type Repo_WriteLoginLog_Call struct {
	*mock.Call
}

// WriteLoginLog is a helper method to define mock.On call
//   - l *auth.UserLoginLog
func (_e *Repo_Expecter) WriteLoginLog(l interface{}) *Repo_WriteLoginLog_Call {
	return &Repo_WriteLoginLog_Call{Call: _e.mock.On("WriteLoginLog", l)}
}

func (_c *Repo_WriteLoginLog_Call) Run(run func(l *auth.UserLoginLog)) *Repo_WriteLoginLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.UserLoginLog))
	})
	return _c
}

func (_c *Repo_WriteLoginLog_Call) Return(_a0 error) *Repo_WriteLoginLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_WriteLoginLog_Call) RunAndReturn(run func(*auth.UserLoginLog) error) *Repo_WriteLoginLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
