// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	user "github.com/yyypluto/parkieee-api/internal/user"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

type Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *Repo) EXPECT() *Repo_Expecter {
	return &Repo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: u
func (_m *Repo) CreateUser(u *user.User) error {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*user.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Repo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - u *user.User
func (_e *Repo_Expecter) CreateUser(u interface{}) *Repo_CreateUser_Call {
	return &Repo_CreateUser_Call{Call: _e.mock.On("CreateUser", u)}
}

func (_c *Repo_CreateUser_Call) Run(run func(u *user.User)) *Repo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*user.User))
	})
	return _c
}

func (_c *Repo_CreateUser_Call) Return(_a0 error) *Repo_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_CreateUser_Call) RunAndReturn(run func(*user.User) error) *Repo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function with given fields: id
func (_m *Repo) FindUserByID(id uuid.UUID) (*user.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*user.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *user.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type Repo_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repo_Expecter) FindUserByID(id interface{}) *Repo_FindUserByID_Call {
	return &Repo_FindUserByID_Call{Call: _e.mock.On("FindUserByID", id)}
}

func (_c *Repo_FindUserByID_Call) Run(run func(id uuid.UUID)) *Repo_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_FindUserByID_Call) Return(_a0 *user.User, _a1 error) *Repo_FindUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindUserByID_Call) RunAndReturn(run func(uuid.UUID) (*user.User, error)) *Repo_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function with given fields: username
func (_m *Repo) FindUserByUsername(username string) (*user.User, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*user.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type Repo_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - username string
func (_e *Repo_Expecter) FindUserByUsername(username interface{}) *Repo_FindUserByUsername_Call {
	return &Repo_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", username)}
}

func (_c *Repo_FindUserByUsername_Call) Run(run func(username string)) *Repo_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repo_FindUserByUsername_Call) Return(_a0 *user.User, _a1 error) *Repo_FindUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindUserByUsername_Call) RunAndReturn(run func(string) (*user.User, error)) *Repo_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: filter
func (_m *Repo) ListUsers(filter user.ListFilter) ([]user.User, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []user.User
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(user.ListFilter) ([]user.User, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(user.ListFilter) []user.User); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(user.ListFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(user.ListFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repo_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type Repo_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - filter user.ListFilter
func (_e *Repo_Expecter) ListUsers(filter interface{}) *Repo_ListUsers_Call {
	return &Repo_ListUsers_Call{Call: _e.mock.On("ListUsers", filter)}
}

func (_c *Repo_ListUsers_Call) Run(run func(filter user.ListFilter)) *Repo_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(user.ListFilter))
	})
	return _c
}

func (_c *Repo_ListUsers_Call) Return(_a0 []user.User, _a1 int64, _a2 error) *Repo_ListUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repo_ListUsers_Call) RunAndReturn(run func(user.ListFilter) ([]user.User, int64, error)) *Repo_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RoleExists provides a mock function with given fields: roleID
func (_m *Repo) RoleExists(roleID uuid.UUID) (bool, error) {
	ret := _m.Called(roleID)

	if len(ret) == 0 {
		panic("no return value specified for RoleExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (bool, error)); ok {
		return rf(roleID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(roleID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_RoleExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleExists'
type Repo_RoleExists_Call struct {
	*mock.Call
}

// RoleExists is a helper method to define mock.On call
//   - roleID uuid.UUID
func (_e *Repo_Expecter) RoleExists(roleID interface{}) *Repo_RoleExists_Call {
	return &Repo_RoleExists_Call{Call: _e.mock.On("RoleExists", roleID)}
}

func (_c *Repo_RoleExists_Call) Run(run func(roleID uuid.UUID)) *Repo_RoleExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_RoleExists_Call) Return(_a0 bool, _a1 error) *Repo_RoleExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_RoleExists_Call) RunAndReturn(run func(uuid.UUID) (bool, error)) *Repo_RoleExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserActive provides a mock function with given fields: id, isActive
func (_m *Repo) SetUserActive(id uuid.UUID, isActive bool) error {
	ret := _m.Called(id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetUserActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, bool) error); ok {
		r0 = rf(id, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_SetUserActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserActive'
type Repo_SetUserActive_Call struct {
	*mock.Call
}

// SetUserActive is a helper method to define mock.On call
//   - id uuid.UUID
//   - isActive bool
func (_e *Repo_Expecter) SetUserActive(id interface{}, isActive interface{}) *Repo_SetUserActive_Call {
	return &Repo_SetUserActive_Call{Call: _e.mock.On("SetUserActive", id, isActive)}
}

func (_c *Repo_SetUserActive_Call) Run(run func(id uuid.UUID, isActive bool)) *Repo_SetUserActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(bool))
	})
	return _c
}

func (_c *Repo_SetUserActive_Call) Return(_a0 error) *Repo_SetUserActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_SetUserActive_Call) RunAndReturn(run func(uuid.UUID, bool) error) *Repo_SetUserActive_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: id, passwordHash
func (_m *Repo) UpdatePassword(id uuid.UUID, passwordHash string) error {
	ret := _m.Called(id, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(id, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type Repo_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - id uuid.UUID
//   - passwordHash string
func (_e *Repo_Expecter) UpdatePassword(id interface{}, passwordHash interface{}) *Repo_UpdatePassword_Call {
	return &Repo_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", id, passwordHash)}
}

func (_c *Repo_UpdatePassword_Call) Run(run func(id uuid.UUID, passwordHash string)) *Repo_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *Repo_UpdatePassword_Call) Return(_a0 error) *Repo_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_UpdatePassword_Call) RunAndReturn(run func(uuid.UUID, string) error) *Repo_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: u
func (_m *Repo) UpdateUser(u *user.User) error {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*user.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Repo_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - u *user.User
func (_e *Repo_Expecter) UpdateUser(u interface{}) *Repo_UpdateUser_Call {
	return &Repo_UpdateUser_Call{Call: _e.mock.On("UpdateUser", u)}
}

func (_c *Repo_UpdateUser_Call) Run(run func(u *user.User)) *Repo_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*user.User))
	})
	return _c
}

func (_c *Repo_UpdateUser_Call) Return(_a0 error) *Repo_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_UpdateUser_Call) RunAndReturn(run func(*user.User) error) *Repo_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
