// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	vehicle "github.com/yyypluto/parkieee-api/internal/vehicle"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

type Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *Repo) EXPECT() *Repo_Expecter {
	return &Repo_Expecter{mock: &_m.Mock}
}

// CreateRFIDCard provides a mock function with given fields: c
func (_m *Repo) CreateRFIDCard(c *vehicle.RFIDCard) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateRFIDCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*vehicle.RFIDCard) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_CreateRFIDCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRFIDCard'
type Repo_CreateRFIDCard_Call struct {
	*mock.Call
}

// CreateRFIDCard is a helper method to define mock.On call
//   - c *vehicle.RFIDCard
func (_e *Repo_Expecter) CreateRFIDCard(c interface{}) *Repo_CreateRFIDCard_Call {
	return &Repo_CreateRFIDCard_Call{Call: _e.mock.On("CreateRFIDCard", c)}
}

func (_c *Repo_CreateRFIDCard_Call) Run(run func(c *vehicle.RFIDCard)) *Repo_CreateRFIDCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*vehicle.RFIDCard))
	})
	return _c
}

func (_c *Repo_CreateRFIDCard_Call) Return(_a0 error) *Repo_CreateRFIDCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_CreateRFIDCard_Call) RunAndReturn(run func(*vehicle.RFIDCard) error) *Repo_CreateRFIDCard_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVehicle provides a mock function with given fields: v
func (_m *Repo) CreateVehicle(v *vehicle.Vehicle) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for CreateVehicle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*vehicle.Vehicle) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_CreateVehicle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVehicle'
type Repo_CreateVehicle_Call struct {
	*mock.Call
}

// CreateVehicle is a helper method to define mock.On call
//   - v *vehicle.Vehicle
func (_e *Repo_Expecter) CreateVehicle(v interface{}) *Repo_CreateVehicle_Call {
	return &Repo_CreateVehicle_Call{Call: _e.mock.On("CreateVehicle", v)}
}

func (_c *Repo_CreateVehicle_Call) Run(run func(v *vehicle.Vehicle)) *Repo_CreateVehicle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*vehicle.Vehicle))
	})
	return _c
}

func (_c *Repo_CreateVehicle_Call) Return(_a0 error) *Repo_CreateVehicle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_CreateVehicle_Call) RunAndReturn(run func(*vehicle.Vehicle) error) *Repo_CreateVehicle_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVehicleType provides a mock function with given fields: vt
func (_m *Repo) CreateVehicleType(vt *vehicle.VehicleType) error {
	ret := _m.Called(vt)

	if len(ret) == 0 {
		panic("no return value specified for CreateVehicleType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*vehicle.VehicleType) error); ok {
		r0 = rf(vt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_CreateVehicleType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVehicleType'
type Repo_CreateVehicleType_Call struct {
	*mock.Call
}

// CreateVehicleType is a helper method to define mock.On call
//   - vt *vehicle.VehicleType
func (_e *Repo_Expecter) CreateVehicleType(vt interface{}) *Repo_CreateVehicleType_Call {
	return &Repo_CreateVehicleType_Call{Call: _e.mock.On("CreateVehicleType", vt)}
}

func (_c *Repo_CreateVehicleType_Call) Run(run func(vt *vehicle.VehicleType)) *Repo_CreateVehicleType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*vehicle.VehicleType))
	})
	return _c
}

func (_c *Repo_CreateVehicleType_Call) Return(_a0 error) *Repo_CreateVehicleType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_CreateVehicleType_Call) RunAndReturn(run func(*vehicle.VehicleType) error) *Repo_CreateVehicleType_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateRFID provides a mock function with given fields: id, actorID, deactivatedAt
func (_m *Repo) DeactivateRFID(id uuid.UUID, actorID uuid.UUID, deactivatedAt time.Time) error {
	ret := _m.Called(id, actorID, deactivatedAt)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateRFID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, time.Time) error); ok {
		r0 = rf(id, actorID, deactivatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_DeactivateRFID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateRFID'
type Repo_DeactivateRFID_Call struct {
	*mock.Call
}

// DeactivateRFID is a helper method to define mock.On call
//   - id uuid.UUID
//   - actorID uuid.UUID
//   - deactivatedAt time.Time
func (_e *Repo_Expecter) DeactivateRFID(id interface{}, actorID interface{}, deactivatedAt interface{}) *Repo_DeactivateRFID_Call {
	return &Repo_DeactivateRFID_Call{Call: _e.mock.On("DeactivateRFID", id, actorID, deactivatedAt)}
}

func (_c *Repo_DeactivateRFID_Call) Run(run func(id uuid.UUID, actorID uuid.UUID, deactivatedAt time.Time)) *Repo_DeactivateRFID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *Repo_DeactivateRFID_Call) Return(_a0 error) *Repo_DeactivateRFID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_DeactivateRFID_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID, time.Time) error) *Repo_DeactivateRFID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVehicleType provides a mock function with given fields: id
func (_m *Repo) DeleteVehicleType(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVehicleType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_DeleteVehicleType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVehicleType'
type Repo_DeleteVehicleType_Call struct {
	*mock.Call
}

// DeleteVehicleType is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repo_Expecter) DeleteVehicleType(id interface{}) *Repo_DeleteVehicleType_Call {
	return &Repo_DeleteVehicleType_Call{Call: _e.mock.On("DeleteVehicleType", id)}
}

func (_c *Repo_DeleteVehicleType_Call) Run(run func(id uuid.UUID)) *Repo_DeleteVehicleType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_DeleteVehicleType_Call) Return(_a0 error) *Repo_DeleteVehicleType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_DeleteVehicleType_Call) RunAndReturn(run func(uuid.UUID) error) *Repo_DeleteVehicleType_Call {
	_c.Call.Return(run)
	return _c
}

// FindRFIDByCardUID provides a mock function with given fields: cardUID
func (_m *Repo) FindRFIDByCardUID(cardUID string) (*vehicle.RFIDCard, error) {
	ret := _m.Called(cardUID)

	if len(ret) == 0 {
		panic("no return value specified for FindRFIDByCardUID")
	}

	var r0 *vehicle.RFIDCard
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*vehicle.RFIDCard, error)); ok {
		return rf(cardUID)
	}
	if rf, ok := ret.Get(0).(func(string) *vehicle.RFIDCard); ok {
		r0 = rf(cardUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vehicle.RFIDCard)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cardUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindRFIDByCardUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRFIDByCardUID'
type Repo_FindRFIDByCardUID_Call struct {
	*mock.Call
}

// FindRFIDByCardUID is a helper method to define mock.On call
//   - cardUID string
func (_e *Repo_Expecter) FindRFIDByCardUID(cardUID interface{}) *Repo_FindRFIDByCardUID_Call {
	return &Repo_FindRFIDByCardUID_Call{Call: _e.mock.On("FindRFIDByCardUID", cardUID)}
}

func (_c *Repo_FindRFIDByCardUID_Call) Run(run func(cardUID string)) *Repo_FindRFIDByCardUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repo_FindRFIDByCardUID_Call) Return(_a0 *vehicle.RFIDCard, _a1 error) *Repo_FindRFIDByCardUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindRFIDByCardUID_Call) RunAndReturn(run func(string) (*vehicle.RFIDCard, error)) *Repo_FindRFIDByCardUID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRFIDByID provides a mock function with given fields: id
func (_m *Repo) FindRFIDByID(id uuid.UUID) (*vehicle.RFIDCard, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindRFIDByID")
	}

	var r0 *vehicle.RFIDCard
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*vehicle.RFIDCard, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *vehicle.RFIDCard); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vehicle.RFIDCard)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindRFIDByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRFIDByID'
type Repo_FindRFIDByID_Call struct {
	*mock.Call
}

// FindRFIDByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repo_Expecter) FindRFIDByID(id interface{}) *Repo_FindRFIDByID_Call {
	return &Repo_FindRFIDByID_Call{Call: _e.mock.On("FindRFIDByID", id)}
}

func (_c *Repo_FindRFIDByID_Call) Run(run func(id uuid.UUID)) *Repo_FindRFIDByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_FindRFIDByID_Call) Return(_a0 *vehicle.RFIDCard, _a1 error) *Repo_FindRFIDByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindRFIDByID_Call) RunAndReturn(run func(uuid.UUID) (*vehicle.RFIDCard, error)) *Repo_FindRFIDByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindVehicleByID provides a mock function with given fields: id
func (_m *Repo) FindVehicleByID(id uuid.UUID) (*vehicle.Vehicle, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindVehicleByID")
	}

	var r0 *vehicle.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*vehicle.Vehicle, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *vehicle.Vehicle); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vehicle.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindVehicleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVehicleByID'
type Repo_FindVehicleByID_Call struct {
	*mock.Call
}

// FindVehicleByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repo_Expecter) FindVehicleByID(id interface{}) *Repo_FindVehicleByID_Call {
	return &Repo_FindVehicleByID_Call{Call: _e.mock.On("FindVehicleByID", id)}
}

func (_c *Repo_FindVehicleByID_Call) Run(run func(id uuid.UUID)) *Repo_FindVehicleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_FindVehicleByID_Call) Return(_a0 *vehicle.Vehicle, _a1 error) *Repo_FindVehicleByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindVehicleByID_Call) RunAndReturn(run func(uuid.UUID) (*vehicle.Vehicle, error)) *Repo_FindVehicleByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindVehicleTypeByID provides a mock function with given fields: id
func (_m *Repo) FindVehicleTypeByID(id uuid.UUID) (*vehicle.VehicleType, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindVehicleTypeByID")
	}

	var r0 *vehicle.VehicleType
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*vehicle.VehicleType, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *vehicle.VehicleType); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vehicle.VehicleType)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindVehicleTypeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVehicleTypeByID'
type Repo_FindVehicleTypeByID_Call struct {
	*mock.Call
}

// FindVehicleTypeByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repo_Expecter) FindVehicleTypeByID(id interface{}) *Repo_FindVehicleTypeByID_Call {
	return &Repo_FindVehicleTypeByID_Call{Call: _e.mock.On("FindVehicleTypeByID", id)}
}

func (_c *Repo_FindVehicleTypeByID_Call) Run(run func(id uuid.UUID)) *Repo_FindVehicleTypeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_FindVehicleTypeByID_Call) Return(_a0 *vehicle.VehicleType, _a1 error) *Repo_FindVehicleTypeByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindVehicleTypeByID_Call) RunAndReturn(run func(uuid.UUID) (*vehicle.VehicleType, error)) *Repo_FindVehicleTypeByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindVehicleTypeByName provides a mock function with given fields: name
func (_m *Repo) FindVehicleTypeByName(name string) (*vehicle.VehicleType, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindVehicleTypeByName")
	}

	var r0 *vehicle.VehicleType
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*vehicle.VehicleType, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *vehicle.VehicleType); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vehicle.VehicleType)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_FindVehicleTypeByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVehicleTypeByName'
type Repo_FindVehicleTypeByName_Call struct {
	*mock.Call
}

// FindVehicleTypeByName is a helper method to define mock.On call
//   - name string
func (_e *Repo_Expecter) FindVehicleTypeByName(name interface{}) *Repo_FindVehicleTypeByName_Call {
	return &Repo_FindVehicleTypeByName_Call{Call: _e.mock.On("FindVehicleTypeByName", name)}
}

func (_c *Repo_FindVehicleTypeByName_Call) Run(run func(name string)) *Repo_FindVehicleTypeByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repo_FindVehicleTypeByName_Call) Return(_a0 *vehicle.VehicleType, _a1 error) *Repo_FindVehicleTypeByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_FindVehicleTypeByName_Call) RunAndReturn(run func(string) (*vehicle.VehicleType, error)) *Repo_FindVehicleTypeByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListRFIDCardsByVehicle provides a mock function with given fields: vehicleID, isActive
func (_m *Repo) ListRFIDCardsByVehicle(vehicleID uuid.UUID, isActive *bool) ([]vehicle.RFIDCard, error) {
	ret := _m.Called(vehicleID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for ListRFIDCardsByVehicle")
	}

	var r0 []vehicle.RFIDCard
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *bool) ([]vehicle.RFIDCard, error)); ok {
		return rf(vehicleID, isActive)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *bool) []vehicle.RFIDCard); ok {
		r0 = rf(vehicleID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vehicle.RFIDCard)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *bool) error); ok {
		r1 = rf(vehicleID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_ListRFIDCardsByVehicle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRFIDCardsByVehicle'
type Repo_ListRFIDCardsByVehicle_Call struct {
	*mock.Call
}

// ListRFIDCardsByVehicle is a helper method to define mock.On call
//   - vehicleID uuid.UUID
//   - isActive *bool
func (_e *Repo_Expecter) ListRFIDCardsByVehicle(vehicleID interface{}, isActive interface{}) *Repo_ListRFIDCardsByVehicle_Call {
	return &Repo_ListRFIDCardsByVehicle_Call{Call: _e.mock.On("ListRFIDCardsByVehicle", vehicleID, isActive)}
}

func (_c *Repo_ListRFIDCardsByVehicle_Call) Run(run func(vehicleID uuid.UUID, isActive *bool)) *Repo_ListRFIDCardsByVehicle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(*bool))
	})
	return _c
}

func (_c *Repo_ListRFIDCardsByVehicle_Call) Return(_a0 []vehicle.RFIDCard, _a1 error) *Repo_ListRFIDCardsByVehicle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_ListRFIDCardsByVehicle_Call) RunAndReturn(run func(uuid.UUID, *bool) ([]vehicle.RFIDCard, error)) *Repo_ListRFIDCardsByVehicle_Call {
	_c.Call.Return(run)
	return _c
}

// ListVehicleTypes provides a mock function with given fields: filter
func (_m *Repo) ListVehicleTypes(filter vehicle.VehicleTypeListFilter) ([]vehicle.VehicleType, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListVehicleTypes")
	}

	var r0 []vehicle.VehicleType
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(vehicle.VehicleTypeListFilter) ([]vehicle.VehicleType, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(vehicle.VehicleTypeListFilter) []vehicle.VehicleType); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vehicle.VehicleType)
		}
	}

	if rf, ok := ret.Get(1).(func(vehicle.VehicleTypeListFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(vehicle.VehicleTypeListFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repo_ListVehicleTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVehicleTypes'
type Repo_ListVehicleTypes_Call struct {
	*mock.Call
}

// ListVehicleTypes is a helper method to define mock.On call
//   - filter vehicle.VehicleTypeListFilter
func (_e *Repo_Expecter) ListVehicleTypes(filter interface{}) *Repo_ListVehicleTypes_Call {
	return &Repo_ListVehicleTypes_Call{Call: _e.mock.On("ListVehicleTypes", filter)}
}

func (_c *Repo_ListVehicleTypes_Call) Run(run func(filter vehicle.VehicleTypeListFilter)) *Repo_ListVehicleTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(vehicle.VehicleTypeListFilter))
	})
	return _c
}

func (_c *Repo_ListVehicleTypes_Call) Return(_a0 []vehicle.VehicleType, _a1 int64, _a2 error) *Repo_ListVehicleTypes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repo_ListVehicleTypes_Call) RunAndReturn(run func(vehicle.VehicleTypeListFilter) ([]vehicle.VehicleType, int64, error)) *Repo_ListVehicleTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ListVehicles provides a mock function with given fields: filter
func (_m *Repo) ListVehicles(filter vehicle.VehicleListFilter) ([]vehicle.Vehicle, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListVehicles")
	}

	var r0 []vehicle.Vehicle
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(vehicle.VehicleListFilter) ([]vehicle.Vehicle, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(vehicle.VehicleListFilter) []vehicle.Vehicle); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vehicle.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(vehicle.VehicleListFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(vehicle.VehicleListFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repo_ListVehicles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVehicles'
type Repo_ListVehicles_Call struct {
	*mock.Call
}

// ListVehicles is a helper method to define mock.On call
//   - filter vehicle.VehicleListFilter
func (_e *Repo_Expecter) ListVehicles(filter interface{}) *Repo_ListVehicles_Call {
	return &Repo_ListVehicles_Call{Call: _e.mock.On("ListVehicles", filter)}
}

func (_c *Repo_ListVehicles_Call) Run(run func(filter vehicle.VehicleListFilter)) *Repo_ListVehicles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(vehicle.VehicleListFilter))
	})
	return _c
}

func (_c *Repo_ListVehicles_Call) Return(_a0 []vehicle.Vehicle, _a1 int64, _a2 error) *Repo_ListVehicles_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repo_ListVehicles_Call) RunAndReturn(run func(vehicle.VehicleListFilter) ([]vehicle.Vehicle, int64, error)) *Repo_ListVehicles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVehicle provides a mock function with given fields: v
func (_m *Repo) UpdateVehicle(v *vehicle.Vehicle) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVehicle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*vehicle.Vehicle) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_UpdateVehicle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVehicle'
type Repo_UpdateVehicle_Call struct {
	*mock.Call
}

// UpdateVehicle is a helper method to define mock.On call
//   - v *vehicle.Vehicle
func (_e *Repo_Expecter) UpdateVehicle(v interface{}) *Repo_UpdateVehicle_Call {
	return &Repo_UpdateVehicle_Call{Call: _e.mock.On("UpdateVehicle", v)}
}

func (_c *Repo_UpdateVehicle_Call) Run(run func(v *vehicle.Vehicle)) *Repo_UpdateVehicle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*vehicle.Vehicle))
	})
	return _c
}

func (_c *Repo_UpdateVehicle_Call) Return(_a0 error) *Repo_UpdateVehicle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_UpdateVehicle_Call) RunAndReturn(run func(*vehicle.Vehicle) error) *Repo_UpdateVehicle_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVehicleType provides a mock function with given fields: vt
func (_m *Repo) UpdateVehicleType(vt *vehicle.VehicleType) error {
	ret := _m.Called(vt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVehicleType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*vehicle.VehicleType) error); ok {
		r0 = rf(vt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_UpdateVehicleType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVehicleType'
type Repo_UpdateVehicleType_Call struct {
	*mock.Call
}

// UpdateVehicleType is a helper method to define mock.On call
//   - vt *vehicle.VehicleType
func (_e *Repo_Expecter) UpdateVehicleType(vt interface{}) *Repo_UpdateVehicleType_Call {
	return &Repo_UpdateVehicleType_Call{Call: _e.mock.On("UpdateVehicleType", vt)}
}

func (_c *Repo_UpdateVehicleType_Call) Run(run func(vt *vehicle.VehicleType)) *Repo_UpdateVehicleType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*vehicle.VehicleType))
	})
	return _c
}

func (_c *Repo_UpdateVehicleType_Call) Return(_a0 error) *Repo_UpdateVehicleType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_UpdateVehicleType_Call) RunAndReturn(run func(*vehicle.VehicleType) error) *Repo_UpdateVehicleType_Call {
	_c.Call.Return(run)
	return _c
}

// VehicleTypeInUse provides a mock function with given fields: id
func (_m *Repo) VehicleTypeInUse(id uuid.UUID) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for VehicleTypeInUse")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_VehicleTypeInUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VehicleTypeInUse'
type Repo_VehicleTypeInUse_Call struct {
	*mock.Call
}

// VehicleTypeInUse is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repo_Expecter) VehicleTypeInUse(id interface{}) *Repo_VehicleTypeInUse_Call {
	return &Repo_VehicleTypeInUse_Call{Call: _e.mock.On("VehicleTypeInUse", id)}
}

func (_c *Repo_VehicleTypeInUse_Call) Run(run func(id uuid.UUID)) *Repo_VehicleTypeInUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repo_VehicleTypeInUse_Call) Return(_a0 bool, _a1 error) *Repo_VehicleTypeInUse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_VehicleTypeInUse_Call) RunAndReturn(run func(uuid.UUID) (bool, error)) *Repo_VehicleTypeInUse_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
