// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	audit "github.com/yyypluto/parkieee-api/internal/audit"

	time "time"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// Create provides a mock function with given fields: log
func (_m *Repo) Create(log *audit.AuditLog) error {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*audit.AuditLog) error); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: query, before, limit
func (_m *Repo) Search(query string, before time.Time, limit int) ([]audit.AuditLog, error) {
	ret := _m.Called(query, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []audit.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, int) ([]audit.AuditLog, error)); ok {
		return rf(query, before, limit)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, int) []audit.AuditLog); ok {
		r0 = rf(query, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]audit.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, int) error); ok {
		r1 = rf(query, before, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
