// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	fee "github.com/yyypluto/parkieee-api/internal/fee"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// ListSystemConfigs provides a mock function with no fields
func (_m *Repo) ListSystemConfigs() ([]fee.SystemConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListSystemConfigs")
	}

	var r0 []fee.SystemConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]fee.SystemConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []fee.SystemConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fee.SystemConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSystemConfig provides a mock function with given fields: key, value
func (_m *Repo) UpdateSystemConfig(key string, value string) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSystemConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
