// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	override "github.com/yyypluto/parkieee-api/internal/override"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// CountTodayByOperator provides a mock function with given fields: operatorID
func (_m *Repo) CountTodayByOperator(operatorID uuid.UUID) (int64, error) {
	ret := _m.Called(operatorID)

	if len(ret) == 0 {
		panic("no return value specified for CountTodayByOperator")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (int64, error)); ok {
		return rf(operatorID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) int64); ok {
		r0 = rf(operatorID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(operatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: tx, o
func (_m *Repo) Create(tx *gorm.DB, o *override.OperatorOverride) error {
	ret := _m.Called(tx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *override.OperatorOverride) error); ok {
		r0 = rf(tx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActiveConfig provides a mock function with no fields
func (_m *Repo) FindActiveConfig() (*override.LocalConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindActiveConfig")
	}

	var r0 *override.LocalConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*override.LocalConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *override.LocalConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*override.LocalConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTransaction provides a mock function with given fields: id
func (_m *Repo) FindTransaction(id uuid.UUID) (*override.LocalTx, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindTransaction")
	}

	var r0 *override.LocalTx
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*override.LocalTx, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *override.LocalTx); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*override.LocalTx)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransactionFee provides a mock function with given fields: tx, id, fee
func (_m *Repo) UpdateTransactionFee(tx *gorm.DB, id uuid.UUID, fee int) error {
	ret := _m.Called(tx, id, fee)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionFee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID, int) error); ok {
		r0 = rf(tx, id, fee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
