// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	notification "github.com/yyypluto/parkieee-api/internal/notification"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// Create provides a mock function with given fields: n
func (_m *Repo) Create(n *notification.Notification) error {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*notification.Notification) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountUnread provides a mock function with given fields: userID
func (_m *Repo) CountUnread(userID *uuid.UUID) (int64, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*uuid.UUID) (int64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(*uuid.UUID) int64); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: userID, page, limit
func (_m *Repo) FindByUserID(userID *uuid.UUID, page int, limit int) ([]notification.Notification, int64, error) {
	ret := _m.Called(userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []notification.Notification
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(*uuid.UUID, int, int) ([]notification.Notification, int64, error)); ok {
		return rf(userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(*uuid.UUID, int, int) []notification.Notification); ok {
		r0 = rf(userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(*uuid.UUID, int, int) int64); ok {
		r1 = rf(userID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(*uuid.UUID, int, int) error); ok {
		r2 = rf(userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkAllRead provides a mock function with given fields: userID
func (_m *Repo) MarkAllRead(userID *uuid.UUID) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*uuid.UUID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkRead provides a mock function with given fields: id
func (_m *Repo) MarkRead(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
